export { ReactComponent as IcAlert } from "./alertIcon.svg";
export { ReactComponent as IcBookcase } from "./bookcaseIcon.svg";
export { ReactComponent as IcCancel } from "./cancelIcon.svg";
export { ReactComponent as IcCool } from "./coolIcon.svg";
export { ReactComponent as IcHome } from "./homeIcon.svg";
export { ReactComponent as IcLogo } from "./logoIcon.svg";
export { ReactComponent as IcMyPage } from "./myPageIcon.svg";
export { ReactComponent as IcSearch } from "./searchIcon.svg";
export { ReactComponent as IcToBe } from "./toBeIcon.svg";
